name: Publish Python Package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.check-version.outputs.version-changed }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: ./.github/actions/filter-version
        name: Check version
        id: check-version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
